global using AutoMapper;
global using CourseCatalog.Application.Dtos;
global using CourseCatalog.Application.Exceptions;
global using CourseCatalog.Domain.Aggregates;
global using CourseCatalog.Domain.Enums;
global using CourseCatalog.Domain.Interfaces;
global using CourseCatalog.Domain.Repositories;
global using CourseCatalog.Domain.ValueObjects;
global using MediatR;
