global using AutoMapper;
global using CourseCatalog.Application;
global using CourseCatalog.Application.Commands;
global using CourseCatalog.Application.Queries;
global using CourseCatalog.Contracts.Requests;
global using CourseCatalog.Contracts.Responses;
global using CourseCatalog.Infrastructure;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
